### ISSUE TITLE
 Broken JavaScript and Right Access Issue

### ISSUE THREAD

**Issue by RJP43** [RJP43/STD_UPG#6]
@ebeshero If you get a chance could you look at my JavaScript on the [updated Sigma Tau Delta site](https://github.com/RJP43/STD_UPG/tree/master/Website) and help me figure out what I am doing wrong in the commented out section. It's sitting inside of the styles folder inside of that main folder. The JavaScript is supposed to be displaying a `<p>` element that is otherwise hidden until mouse over I wrote 4 functions because the mouse over is for two parts of an image map and I want the text only to pop up when mousing over the specific related part and disappear when user moves the mouse away. The associated HTML for this part of the JavaScript file is titled ISabout.html 

Also I attempted to remove the old files in the Pitt space where the Sigma Tau Delta site sits and it seems I only have right access to add files (like how I have been when we add to the site for conference) but not remove any files/folders. This might be easier to try and figure out in person but I figured I would give you the heads up of that issue as well.

**Comment by ebeshero** [comment]
@RJP43   write me privately how you are accessing the site--how you're SFTP-ing into it.

**Comment by RJP43** [comment]
@nlottig94 bootstrapped a way to do what I wanted to do from the dickinson16 project. We just added the text by adding an attribute to the image mapping elements. 

@ebeshero I will address the rights access issue with the IT guys.
